baseurl = "/"
languageCode = "en-us"
title = "David Aikman"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[menu]

    [[menu.main]]
        name = "Portfolio"
        url = "https://daikman.github.io/#/portfolio"
        weight = 60
    [[menu.main]]
        name = "Blog"
        url = "/"
        weight = 70
    [[menu.main]]
        name = "About Me"
        url = "/about/"
        weight = 80
        
[params]
    description = "My (David Aikman) website. Built with Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "medrawing.png"
    width = 200
    height = 200
    alt = "Logo"
    
    [params.socials]
    facebook = ""
    twitter = "twitter.com/davidjaikman"
    instagram = ""
    youtube = ""
    github = "github.com/daikman"
    gitlab = ""
    linkedin = ""
    slack = ""
    stackoverflow = ""
    medium= ""


